/**
 * Generates an `index.js` file in this directory with,
 *  - all of the parrot gifs in the folder as import statements
 *  - all of the parrots in an array
 *
 * @CMD `npm run parrots`
 */

const fs = require('fs');
const path = require('path');
const directory = __dirname;

const files = fs.readdirSync(directory);
const gifs = files.filter(file => file.endsWith('.gif'));

const parrots = gifs.map((gif, index) => ({
  name: `parrot${index}`,
  import: `import parrot${index} from './${gif}';`,
}));

const file = `
/**
 * This file was automatically generated by '_generate.js'.
 * Edit at your own risk!
 */

${parrots.map(parrot => parrot.import).join('\n')}

const parrots = [
  ${parrots.map(parrot => parrot.name).join(',\n  ')}
];

export default parrots;
`;

const indexPath = path.join(directory, '/index.js');
fs.writeFileSync(indexPath, file);
