
/**
 * This file was automatically generated by '_generate.js'.
 * Edit at your own risk!
 */

import parrot0 from './angelparrot.gif';
import parrot1 from './angryparrot.gif';
import parrot2 from './aussiecongaparrot.gif';
import parrot3 from './aussieparrot.gif';
import parrot4 from './aussiereversecongaparrot.gif';
import parrot5 from './bananaparrot.gif';
import parrot6 from './beretparrot.gif';
import parrot7 from './birthdaypartyparrot.gif';
import parrot8 from './blondesassyparrot.gif';
import parrot9 from './bluescluesparrot.gif';
import parrot10 from './bluntparrot.gif';
import parrot11 from './boredparrot.gif';
import parrot12 from './ceilingparrot.gif';
import parrot13 from './chillparrot.gif';
import parrot14 from './christmasparrot.gif';
import parrot15 from './coffeeparrot.gif';
import parrot16 from './confusedparrot.gif';
import parrot17 from './congaparrot.gif';
import parrot18 from './congapartyparrot.gif';
import parrot19 from './cryptoparrot.gif';
import parrot20 from './darkbeerparrot.gif';
import parrot21 from './dealwithitparrot.gif';
import parrot22 from './discoparrot.gif';
import parrot23 from './donutparrot.gif';
import parrot24 from './dreidelparrot.gif';
import parrot25 from './evilparrot.gif';
import parrot26 from './explodyparrot.gif';
import parrot27 from './fastparrot.gif';
import parrot28 from './fidgetparrot.gif';
import parrot29 from './fiestaparrot.gif';
import parrot30 from './flyingmoneyparrot.gif';
import parrot31 from './gentlemanparrot.gif';
import parrot32 from './gothparrot.gif';
import parrot33 from './halalparrot.gif';
import parrot34 from './hamburgerparrot.gif';
import parrot35 from './hardhatparrot.gif';
import parrot36 from './harrypotterparrot.gif';
import parrot37 from './ice-cream-parrot.gif';
import parrot38 from './jediparrot.gif';
import parrot39 from './loveparrot.gif';
import parrot40 from './luckyparrot.gif';
import parrot41 from './mardigrasparrot.gif';
import parrot42 from './margaritaparrot.gif';
import parrot43 from './matrixparrot.gif';
import parrot44 from './middleparrot.gif';
import parrot45 from './moonwalkingparrot.gif';
import parrot46 from './oldtimeyparrot.gif';
import parrot47 from './papalparrot.gif';
import parrot48 from './parrot.gif';
import parrot49 from './parrotbeer.gif';
import parrot50 from './parrotcop.gif';
import parrot51 from './parrotdad.gif';
import parrot52 from './parrotmustache.gif';
import parrot53 from './parrotsleep.gif';
import parrot54 from './parrotwave1.gif';
import parrot55 from './parrotwave2.gif';
import parrot56 from './parrotwave3.gif';
import parrot57 from './parrotwave4.gif';
import parrot58 from './parrotwave5.gif';
import parrot59 from './parrotwave6.gif';
import parrot60 from './parrotwave7.gif';
import parrot61 from './partyparrot.gif';
import parrot62 from './pirateparrot.gif';
import parrot63 from './pizzaparrot.gif';
import parrot64 from './popcornparrot.gif';
import parrot65 from './portalparrot.gif';
import parrot66 from './pumpkinparrot.gif';
import parrot67 from './reversecongaparrot.gif';
import parrot68 from './revolutionparrot.gif';
import parrot69 from './rightparrot.gif';
import parrot70 from './rotatingparrot.gif';
import parrot71 from './ryangoslingparrot.gif';
import parrot72 from './sadparrot.gif';
import parrot73 from './sassyparrot.gif';
import parrot74 from './scienceparrot.gif';
import parrot75 from './shipitparrot.gif';
import parrot76 from './shufflefurtherparrot.gif';
import parrot77 from './shuffleparrot.gif';
import parrot78 from './shufflepartyparrot.gif';
import parrot79 from './sintparrot.gif';
import parrot80 from './sithparrot.gif';
import parrot81 from './skiparrot.gif';
import parrot82 from './slomoparrot.gif';
import parrot83 from './slowparrot.gif';
import parrot84 from './sovjetparrot.gif';
import parrot85 from './stableparrot.gif';
import parrot86 from './stalkerparrot.gif';
import parrot87 from './sushiparrot.gif';
import parrot88 from './tacoparrot.gif';
import parrot89 from './thumbsupparrot.gif';
import parrot90 from './tripletsparrot.gif';
import parrot91 from './twinsparrot.gif';
import parrot92 from './ultrafastparrot.gif';
import parrot93 from './upvotepartyparrot.gif';
import parrot94 from './wendyparrot.gif';

const parrots = [
  parrot0,
  parrot1,
  parrot2,
  parrot3,
  parrot4,
  parrot5,
  parrot6,
  parrot7,
  parrot8,
  parrot9,
  parrot10,
  parrot11,
  parrot12,
  parrot13,
  parrot14,
  parrot15,
  parrot16,
  parrot17,
  parrot18,
  parrot19,
  parrot20,
  parrot21,
  parrot22,
  parrot23,
  parrot24,
  parrot25,
  parrot26,
  parrot27,
  parrot28,
  parrot29,
  parrot30,
  parrot31,
  parrot32,
  parrot33,
  parrot34,
  parrot35,
  parrot36,
  parrot37,
  parrot38,
  parrot39,
  parrot40,
  parrot41,
  parrot42,
  parrot43,
  parrot44,
  parrot45,
  parrot46,
  parrot47,
  parrot48,
  parrot49,
  parrot50,
  parrot51,
  parrot52,
  parrot53,
  parrot54,
  parrot55,
  parrot56,
  parrot57,
  parrot58,
  parrot59,
  parrot60,
  parrot61,
  parrot62,
  parrot63,
  parrot64,
  parrot65,
  parrot66,
  parrot67,
  parrot68,
  parrot69,
  parrot70,
  parrot71,
  parrot72,
  parrot73,
  parrot74,
  parrot75,
  parrot76,
  parrot77,
  parrot78,
  parrot79,
  parrot80,
  parrot81,
  parrot82,
  parrot83,
  parrot84,
  parrot85,
  parrot86,
  parrot87,
  parrot88,
  parrot89,
  parrot90,
  parrot91,
  parrot92,
  parrot93,
  parrot94
];

export default parrots;
